### ISSUE TITLE
Roadmap:

### ISSUE THREAD

**Issue by 0sm1um** [0sm1um/pathfinder#1]
- [ ] Implement Grid Style Map
- [ ] Design "terrain", designate one way and intersection tiles as well as blocked off tiles
- [ ] Implement Pathfinding algorithm, to find all paths from one start point to another end point
- [ ] Iterate through start and endpoints and generate sequence of "decisions" for transition models
- [ ] Write function to inputs a decision sequence and time interval, which generates a trajectory with terrain labels
